### PR TITLE
fix: minimum fee used in collateral calc

### LINKED ISSUE #393: setCollateral default is not enough for some transactions
The setCollateral value of 5 ADA set here:
[https://github.com/Anastasia-Labs/lucid-evolution/blob/e88f247a3178ce4847c6700a28eef6ef32463691/packages/lucid/src/tx-builder/internal/CompleteTxBuilder.ts#L106](https://github.com/Anastasia-Labs/lucid-evolution/blob/e88f247a3178ce4847c6700a28eef6ef32463691/packages/lucid/src/tx-builder/internal/CompleteTxBuilder.ts#L106)
is not enough for some transactions.

Trying to submit the following tx:
[transaction.txt](https://github.com/user-attachments/files/17667435/transaction.txt)

resulted in the following error:
`Error: {"contents":{"contents":{"contents":{"era":"ShelleyBasedEraConway","error":["ConwayUtxowFailure (UtxoFailure (InsufficientCollateral (DeltaCoin 5000000) (Coin 6692501)))"],"kind":"ShelleyTxValidationError"},"tag":"TxValidationErrorInCardanoMode"},"tag":"TxCmdTxSubmitValidationError"},"tag":"TxSubmitFail"}`

### PR DESCRIPTION
**Pull request by hadelive**
fix #393

### CODE REVIEW

File: packages/lucid/src/tx-builder/internal/CompleteTxBuilder.ts [hunk 1]
```diff
@@ -131,12 +138,24 @@ export const complete = (options: CompleteOptions = {}) =>
     ).some((value) => value.type !== "Native");
     // Set collateral input if there are script executions
     if (hasPlutusScriptExecutions) {
+      const minFee = config.txBuilder.min_fee(false);
```
Comment (solidsnakedev) [inline packages/lucid/src/tx-builder/internal/CompleteTxBuilder.ts:141]: `minFee` does not include the script calculation

**Review by solidsnakedev — COMMENTED** [review]
LGTM

**Comment by solidsnakedev** [comment]
we should add the missing options to the TxBuilder chain type
```typescript
  chainProgram: () => Effect.Effect<
    [UTxO[], UTxO[], TxSignBuilder.TxSignBuilder],
    TransactionError,
    never
  >;
  chain: () => Promise<[UTxO[], UTxO[], TxSignBuilder.TxSignBuilder]>;
  chainSafe: () => Promise<
    Either<[UTxO[], UTxO[], TxSignBuilder.TxSignBuilder], TransactionError>
  >;
  ```
